/**
 * Single source of truth for the Orama game-data search index schema.
 * Used by the build script (`scripts/build-orama-index.ts`) and the browser loader.
 */
export const ORAMA_DATA_SEARCH_SCHEMA = {
	id: 'string',
	type: 'string',
	title: 'string',
	content: 'string',
	href: 'string',
	subtitle: 'string',
	cardJson: 'string',
	spellTier: 'string',
	spellSchool: 'string',
	spellTarget: 'string',
	spellUtility: 'string',
	spellSecret: 'string',
	monsterLevel: 'string',
	monsterFamily: 'string',
	monsterKind: 'string',
	monsterArmor: 'string',
	monsterSpeed: 'string',
	monsterSize: 'string',
	monsterMinion: 'string',
	monsterLegendary: 'string',
	classKeyStats: 'string',
	classHitDie: 'string',
	weaponCategory: 'string',
	ancestrySection: 'string',
	ancestrySize: 'string',
	armorCategory: 'string',
	magicKind: 'string',
	magicSource: 'string',
	magicReward: 'string',
} as const;
