name: Spell Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1.19.1
    with:
      config: cspell.json
      modified_files_only: false
      includes: |
        **/*.{md,mdx,ts,tsx,astro}
        **/*.{json,yml,yaml}
        !dist/**
        !node_modules/**
        !package-lock.json
        !skills-lock.json
